import { Link } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import logo from '@/assets/logo-header-blue.png';
import { MessageCircle, FileText, Sparkles, ArrowRight } from 'lucide-react';
import DashboardPage from './DashboardPage';
export default function Index() {
  const { user, loading } = useAuth();
  if (loading) return <main className="min-h-screen grid place-items-center"><p role="status">Loading…</p></main>;
  if (user) return <DashboardPage />;
  return <div className="min-h-screen bg-background text-foreground">
    <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:bg-background focus:p-3">Skip to content</a>
    <header className="border-b"><nav aria-label="Main navigation" className="max-w-6xl mx-auto px-5 py-5 flex flex-wrap items-center justify-between gap-4"><Link to="/" aria-label="Syncflow home"><img src={logo} alt="Syncflow" className="h-8" /></Link><div className="flex gap-2"><Button asChild variant="ghost"><Link to="/auth?mode=login">Log in</Link></Button><Button asChild><Link to="/auth?mode=signup">Get started</Link></Button></div></nav></header>
    <main id="main-content" className="max-w-6xl mx-auto px-5">
      <section className="py-20 sm:py-28 grid md:grid-cols-[1.25fr_1fr] gap-12 items-center"><div><p className="text-primary font-medium mb-4">Meet your brand’s creative partner</p><h1 className="text-4xl sm:text-6xl font-bold tracking-tight leading-tight">Turn what makes your brand special into content.</h1><p className="text-lg text-muted-foreground leading-relaxed mt-6 max-w-xl">Teach Syncflow about your business, explore ideas together, and create scripts shaped by your audience, voice and goals.</p><Button asChild size="lg" className="mt-8"><Link to="/auth?mode=signup">Start with your brand <ArrowRight aria-hidden="true" className="ml-2 h-4 w-4" /></Link></Button><p className="text-sm text-muted-foreground mt-4">Early access. AI suggestions need your review.</p></div><div className="bg-primary/5 border rounded-3xl p-7 sm:p-10 space-y-5"><p className="text-sm font-semibold text-primary">A clearer path from idea to script</p>{['Tell us about your business and what you want to achieve.', 'Add brand references and discuss a practical content plan.', 'Generate a script, refine it, and keep your versions together.'].map((text,i) => <div key={text} className="flex gap-4 items-start rounded-xl bg-background p-4 border"><span className="text-primary font-bold">0{i+1}</span><p className="leading-relaxed">{text}</p></div>)}</div></section>
      <section aria-labelledby="features-title" className="pb-20"><h2 id="features-title" className="text-3xl font-bold mb-8">Built around your brand</h2><div className="grid md:grid-cols-3 gap-5">{[{icon:MessageCircle,title:'A conversation with direction',text:'Get help defining your audience, positioning and voice. Save your answers and return whenever you need.'},{icon:FileText,title:'Your knowledge, in one place',text:'Add text, PDF or Word references. Review the extracted text and remove documents you no longer want used.'},{icon:Sparkles,title:'Scripts you can make your own',text:'Create platform-specific scripts, edit the hook and call to action, and keep a history of saved changes.'}].map(({icon:Icon,title,text}) => <article key={title} className="rounded-2xl border p-6"><Icon aria-hidden="true" className="h-7 w-7 text-primary mb-5" /><h3 className="text-xl font-semibold mb-3">{title}</h3><p className="text-muted-foreground leading-relaxed">{text}</p></article>)}</div></section>
      <section className="border-t py-12 max-w-3xl space-y-4"><h2 className="text-2xl font-bold">What happens to my brand information?</h2><p className="text-muted-foreground leading-relaxed">Your profile, reference text and recent conversation help the configured AI service generate suggestions. Share information you want used in your content, and avoid passwords or private customer details. You can delete uploaded references and clear your assistant conversation.</p><p className="text-muted-foreground leading-relaxed">Social publishing, automated inbox replies and billing are being developed. Early access focuses on brand setup, planning and scripts.</p></section>
    </main><footer className="border-t py-8 px-5 text-sm text-muted-foreground"><div className="max-w-6xl mx-auto flex flex-wrap justify-between gap-3"><span>Syncflow · Content starts with understanding your brand.</span><Link to="/auth?mode=login" className="underline">Log in to your workspace</Link></div></footer>
  </div>;
}
