import { useQuery } from '@tanstack/react-query';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import api from '@/lib/apiClient';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
interface Usage { daily_limit: number; used: number; remaining: number; resets_at: string; completed: number; failed: number; in_progress: number; cancelled: number; ai_configured: boolean }
export default function Usage() {
  const { currentWorkspace } = useWorkspace();
  const usage = useQuery({ queryKey: ['workspace-usage', currentWorkspace?.id], enabled: !!currentWorkspace, queryFn: async () => (await api.get<Usage>('/api/ai/workspace-usage/', { params: { workspace: currentWorkspace?.id } })).data });
  const data = usage.data;
  return <div className="mx-auto max-w-5xl p-4 sm:p-8 space-y-6"><header><h1 className="text-3xl font-bold">Usage & limits</h1><p className="text-muted-foreground mt-2">Today’s AI allowance for {currentWorkspace?.name || 'your workspace'}. It is shared across the workspace’s members and brands.</p></header><Button variant="outline" disabled={!currentWorkspace || usage.isFetching} onClick={() => void usage.refetch()}>{usage.isFetching ? 'Refreshing…' : 'Refresh usage'}</Button>{!currentWorkspace && <p>Select a workspace to view its usage.</p>}{usage.isLoading && <p role="status">Loading usage…</p>}{usage.isError && <p role="alert">Usage could not be loaded. Refresh to try again.</p>}{data && <><div className="grid sm:grid-cols-3 gap-4">{[{label:'Requests today',value:data.used},{label:'Daily allowance',value:data.daily_limit},{label:'Requests remaining',value:data.remaining}].map(item => <Card key={item.label}><CardHeader><CardTitle className="text-base">{item.label}</CardTitle></CardHeader><CardContent><p className="text-4xl font-bold">{item.value}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Today’s activity</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-6">{[{label:'Completed',value:data.completed},{label:'Failed',value:data.failed},{label:'In progress',value:data.in_progress},{label:'Cancelled',value:data.cancelled}].map(item => <p key={item.label}><strong>{item.value}</strong> {item.label}</p>)}</div><p className="text-sm text-muted-foreground">Allowance resets at {new Date(data.resets_at).toLocaleString()} in your device’s timezone, at midnight UTC.</p><p className="text-sm text-muted-foreground">Failed and cancelled requests count towards the allowance because a provider request may already have been made. Manual edits, approvals and downloads do not use AI requests.</p>{data.remaining === 0 && <p role="status" className="border rounded-lg p-3">This workspace has reached its daily allowance. Saved content is still available for editing and review.</p>}{!data.ai_configured && <p role="status" className="border rounded-lg p-3">AI setup is pending. You can write your own ideas and edit saved content while setup is completed.</p>}<p className="text-xs text-muted-foreground">Provider quotas can be reached before this workspace allowance. The displayed allowance does not guarantee provider availability.</p></CardContent></Card></>}</div>;
}
